server:
  port: 8585
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
    
spring:
  application:
    name: camunda-external-task-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.132.23.119/oauth
    username: postgres
    password: 123456
#开启Hystrix
feign:
  hystrix:
    enabled: true
  client:
    config:
      rpc-user: # feign name
        requestInterceptors:
          - com.crusoe.fo.externaltask.config.FeignTokenInterceptor