server:
  port: 7000
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
 
spring:
  application:
    name: oauth2-service
  redis:
    host: 127.0.0.1
    database: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/oauth
    username: postgres
    password: postgres1982
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#https://blog.csdn.net/huweijian5/article/details/83008435