zeebe:


  client:
    broker.gatewayAddress: 127.0.0.1:26500
    security.plaintext: true

    worker:
      hazelcast:
        connection: localhost:5701
        connectionTimeout: PT30S

spring:
  cloud:
    config:
      import-check:
        enabled: false
    discovery:
      enabled: true
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: zeebe-service
        heartbeat:
          enabled: true
  application:
    name: zeebe-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/oauth
    username: postgres
    password: postgres1982
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true    

  #datasource:
  #  url: jdbc:h2:mem:zeebe-monitor;DB_CLOSE_DELAY=-1
  #  username: sa
  #  password:
  #  driverClassName: org.h2.Driver

  #jpa:
  #  database-platform: org.hibernate.dialect.H2Dialect
  #  hibernate:
  #    ddl-auto: update


server:
  port: 8089
  servlet:
    context-path: /


logging:
  level:
    root: ERROR
    io.zeebe: INFO
    io.zeebe.monitor: DEBUG
    com.hazelcast: WARN

white-label:
  logo.path: img/logo.png
  custom:
    title: Zeebe Simple Monitor
    css.path: css/custom.css
    js.path: js/custom.js
