server:
  port: 8081

spring:
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:postgres/postgres1982@localhost:5432/postgres
    username: postgres
    password: postgres1982

    


